// File generated by FlutterFire CLI or custom template.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoWebApiKeyPlaceholderProject3Wheel',
    appId: '1:1234567890:web:project3wheels',
    messagingSenderId: '1234567890',
    projectId: 'project3wheels',
    authDomain: 'project3wheels.firebaseapp.com',
    storageBucket: 'project3wheels.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoAndroidApiKeyPlaceholderProject3Wheel',
    appId: '1:1234567890:android:project3wheels',
    messagingSenderId: '1234567890',
    projectId: 'project3wheels',
    storageBucket: 'project3wheels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoIosApiKeyPlaceholderProject3Wheel',
    appId: '1:1234567890:ios:project3wheels',
    messagingSenderId: '1234567890',
    projectId: 'project3wheels',
    storageBucket: 'project3wheels.appspot.com',
    iosBundleId: 'com.project3wheel.app.project3Wheel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoMacosApiKeyPlaceholderProject3Wheel',
    appId: '1:1234567890:macos:project3wheels',
    messagingSenderId: '1234567890',
    projectId: 'project3wheels',
    storageBucket: 'project3wheels.appspot.com',
    iosBundleId: 'com.project3wheel.app.project3Wheel',
  );
}
